#!/bin/bash

#contador para insercion
contador=200

#se crea bandera para salir de ciclos
bandera=0
echo "Se requiere instalar dialog, inicia secion como sudo"
dialog --title "Instalacion requerida" --msgbox "Se requiere gnuplot fbi dialog para continuar, inicia secion como sudo" 0 0
#se requiere instalacion de paquetes especiales
sudo apt-get install gnuplot fbi dialog

#insertar archivo para base de datos
until [ "$bandera" -eq 1 ]
do
        dialog --title "Seleccion de Archivo" --inputbox "Ingresa tu archivo:" 0 0 2>/tmp/a.prueba.$$
	if  [ $? -eq 1 ];
	then
        	clear
	        exit
	fi

        prueba=$(cat /tmp/a.prueba.$$)

        if [ -f "$prueba" ]
        then
                bandera=1
	else 
		 dialog --title "Error" --msgbox "Error no se pudo encontrar el archivo, vuelva a intentarlo" 0 0

        fi
done
bandera=0 #reinicia bandera

#inica secion con MySQL
 
until [ "$bandera" -eq 1 ];
do

dialog --title "Sesion para MySQL" --passwordbox "Ingresa secion para MySQL: " 0 0 2>/tmp/info.tmp.$$
#si pone cancelar, sale automaticamente... asi con cada uno
if  [ $? -eq 1 ];
then
      	clear
	exit
fi

pass=$(cat /tmp/info.tmp.$$) #almacena password en pass
	if [ "$pass" == "toor" ];
	then
		bandera=1
	else
		dialog --msgbox "Error vuelva a intentarlo" 0 0
	fi

done

#si existiera el archivo /tmp/insert significa que antes se creo la base de datos, por lo tanto se elimina
if [ -f /tmp/insert ];
then
	echo "drop database medidas;" > /tmp/insert
	mysql -u root --password="$pass" < /tmp/insert
	rm /tmp/insert
fi

#se crea base de Datos llamada medidas
echo "create database medidas;
use medidas;
create table Info(
Id int AUTO_INCREMENT,
Edad int(100),
Estatura int(220),
Peso int(200),
Promedio int(10),
Sexo varchar(50),
PRIMARY KEY (Id)
);" > /tmp/insert



#toma del archivo datos para la creacion de la BD
while read -r i
do
	Edad=$(echo "$i"| cut -d"," -f3)
	Estatura=$(echo "$i"| cut -d"," -f4)
	Peso=$(echo "$i"| cut -d"," -f5)
	Promedio=$(echo "$i"| cut -d"," -f6)
	Sexo=$(echo "$i"| cut -d"," -f7)
 	echo "insert into Info values ('Id','$Edad','$Estatura','$Peso', '$Promedio', '$Sexo');" >>/tmp/insert 


done <"$prueba"


#no se elimino femenino hasta ahora, asi que se hace un delete para filtrar
echo "Delete from Info where Sexo='feminino';" >> /tmp/insert
#se hace un echo solamente para corroborar si funciona, en caso de comentado es porque funciono
#echo "Select * from Info" >>/tmp/insert


#se incorpora insert para hacer la base de datos y empezar las consultas
mysql -u root --password="$pass" < /tmp/insert
if [ $? -eq 1 ];then
	dialog --title "Error" --msgbox "Error Algo salio mal vuelva a intentarlo" 0 0
fi
bandera=0 #reinicia bandera


#seccion para interfaz de usuario


until [ "$bandera" -eq 2 ]
do
dialog --radiolist "¿Que deseas hacer con la informacion?" 0 0 0 1 "Desplegar info" on 2 "Insertar Informacion" off 3 "Borrar informacion" off 4 "Modificar registros" off 5 "Reportes" off 6 "Salir" off 2>/tmp/info.$$
if  [ $? -eq 1 ];
then
	clear
	exit
fi
slc=$(cat /tmp/info.$$) #almacena el valor seleccionado

#se crea seccion para que despliegue informacion
echo "use medidas;
select * from Info;" > /tmp/sel
#se crea seccion para modificacion de informacion

#se crea seccion para insercion de informacion

#1ra opcion solo despliega la informacion
if [ "$slc" -eq 1 ]; then
bandera=1
until [ "$bandera" -eq 0 ] 
do
        dialog --radiolist "¿Como deseas ver la informacion?" 0 0 0 1 "Por ID" on 2 "Por Estatura" off 3 "Por Edad" off 4 "Por Peso" off 5 "Por Sexo" off 2>/tmp/res.$$
	if  [ $? -eq 1 ];
	then
		bandera=0
	fi
        res=$(cat /tmp/res.$$)
        if [ "$res" -eq 1 ];
        then
		dialog --radiolist "¿Deseas ver todos los ID o uno en especifico?" 0 0 0 1 "Todos" on 2 "Especifico" off 2>/tmp/res2.$$
        	res2=$(cat /tmp/res2.$$)
               	if [ "$res2" -eq 1 ];
          	then
                        dialog --radiolist "¿De forma Ascendente o Desendente?" 0 0 0 1 "Ascendente" on 2 "Descendente" off 2>/tmp/res3.$$
                       	res3=$(cat /tmp/res3.$$)
                       	if [ "$res3" -eq 1 ];
                       	then
                               	echo "use medidas;
				select * from Info
				order by Id;" > /tmp/ia
				mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0
                                bandera=0
			else
				echo "use medidas;
                                select * from Info
                                order by Id DESC;" > /tmp/ia
                                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                                bandera=0
	                fi
		fi
		if [ "$res2" -eq 2 ];
		then
			dialog --title "¿Cual ID desea ver?" --inputbox "Numero del ID:" 0 0 2>/tmp/nom.$$
			nom=$(cat /tmp/nom.$$)
			echo "use medidas;
			select * from Info
			where Id in ("$nom");" > /tmp/ia
			mysql -u root --password="$pass" </tmp/ia >/tmp/arch
		        arch=$(cat /tmp/arch)
                        if [ -z "$arch" ]; then
                                dialog --title "Error" --msgbox "No existe el ID" 0 0
                                bandera=0
                        else
                                dialog --title "Informacion" --textbox "/tmp/arch" 0 0
                        fi


			bandera=0 
		fi
	fi
	if [ "$res" -eq 2 ];
	then
		dialog --radiolist "¿Deseas ver todas las Estaturas o una en especifico?" 0 0 0 1 "Todas" on 2 "Especifico" off 2>/tmp/res2.$$
                res2=$(cat /tmp/res2.$$)
                if [ "$res2" -eq 1 ];
                then
                        dialog --radiolist "¿De forma Ascendente o Desendente?" 0 0 0 1 "Ascendente" on 2 "Descendente" off 2>/tmp/res3.$$
                        res3=$(cat /tmp/res3.$$)
                        if [ "$res3" -eq 1 ];
                        then
                                echo "use medidas;
                                select * from Info
                                order by Estatura;" > /tmp/ia
                                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                                bandera=0
                        else
				echo "use medidas;
                                select * from Info
                                order by Estatura DESC;" > /tmp/ia
                                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                                bandera=0
                        fi
                fi
                if [ "$res2" -eq 2 ];
                then
                        dialog --title "¿Cual Estatura desea ver?" --inputbox "Inserte Numero:" 0 0 2>/tmp/nom.$$
                        nom=$(cat /tmp/nom.$$)
                        echo "use medidas;
                        select * from Info
                        where Id in ("$nom");" > /tmp/ia   
                        mysql -u root --password="$pass" </tmp/ia >/tmp/arch
		        arch=$(cat /tmp/arch)
                        if [ -z "$arch" ]; then
                                dialog --title "Error" --msgbox "No existe el Registro" 0 0
                                bandera=0
                        else
                                dialog --title "Informacion" --textbox "/tmp/arch" 0 0
                        fi


                fi
        fi
	if [ "$res" -eq 3 ];
        then
                dialog --radiolist "¿Deseas ver todas las Edades o una en especifico?" 0 0 0 1 "Todas" on 2 "Especifico" off 2>/tmp/res2.$$
                res2=$(cat /tmp/res2.$$)
                if [ "$res2" -eq 1 ];
                then
                        dialog --radiolist "¿De forma Ascendente o Desendente?" 0 0 0 1 "Ascendente" on 2 "Descendente" off 2>/tmp/res3.$$
                        res3=$(cat /tmp/res3.$$)
                        if [ "$res3" -eq 1 ]
                        then
                                echo "use medidas;
                                select * from Info
                                order by Edad;" >/tmp/ia
                                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                                bandera=0
                        else
                                echo "use medidas;
				select * from Info
                                order by Edad DESC;" >/tmp/ia
                                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                                bandera=0
                        fi
                fi
                if [ "$res2" -eq 2 ];
                then
                        dialog --title "¿Cual Edad desea ver?" --inputbox "Inserte Numero:" 0 0 2>/tmp/nom.$$
                        nom=$(cat /tmp/nom.$$)
                        echo "use medidas;
                        select * from Info
                        where Edad in ("$nom");" > /tmp/ia   
                        mysql -u root --password="$pass" </tmp/ia >/tmp/arch
		        arch=$(cat /tmp/arch)
                        if [ -z "$arch" ]; then
                                dialog --title "Error" --msgbox "No existe el Registro" 0 0
                                bandera=0
                        else
                                dialog --title "Informacion" --textbox "/tmp/arch" 0 0
                        fi


                fi
        fi
	if [ "$res" -eq 4 ];
        then
                dialog --radiolist "¿Deseas ver todas los Pesos o uno en especifico?" 0 0 0 1 "Todos" on 2 "Especifico" off 2>/tmp/res2.$$
                res2=$(cat /tmp/res2.$$)
                if [ "$res2" -eq 1 ];
                then
                        dialog --radiolist "¿De forma Ascendente o Desendente?" 0 0 0 1 "Ascendente" on 2 "Descendente" off 2>/tmp/res3.$$
                        res3=$(cat /tmp/res3.$$)
                        if [ "$res3" -eq 1 ];
                        then
                                echo "use medidas;
                                select * from Info
                                order by Peso;" > /tmp/ia
                                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                                bandera=0
                        else
                                echo "use medidas;
                                select * from Info
                                order by Peso DESC;" > /tmp/ia
                                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
			        arch=$(cat /tmp/arch)
			        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                                bandera=0
                        fi
                fi
                if [ "$res2" -eq 2 ];
                then
                        dialog --title "¿Cual Edad desea ver?" --inputbox "Inserte Numero:" 0 0 2>/tmp/nom.$$
                        nom=$(cat /tmp/nom.$$)
                        echo "use medidas;
                        select * from Info
                        where Peso in ("$nom");"  > /tmp/ia
                        mysql -u root --password="$pass" </tmp/ia >/tmp/arch
		        arch=$(cat /tmp/arch)
                        if [ -z "$arch" ]; then
                                dialog --title "Error" --msgbox "No existe el Registro" 0 0
                                bandera=0
                        else
                                dialog --title "Informacion" --textbox "/tmp/arch" 0 0
                        fi


                fi
        fi
        if [ "$res" -eq 5 ];
        then
                dialog --radiolist "¿Cual Sexo deseas ver?" 0 0 0 1 "Hombres" on 2 "Mujeres" off 2>/tmp/res2.$$
                res2=$(cat /tmp/res2.$$)
                if [ "$res2" -eq 1 ];
                then
			echo "use medidas;
                        select * from Info
                        where Sexo in ('masculino');" > /tmp/ia
                        mysql -u root --password="$pass" </tmp/ia >/tmp/arch
		        arch=$(cat /tmp/arch)
		        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

                        bandera=0
                else
                        echo "use medidas;
                        select * from Info
                        where Sexo in ('femenino');" > /tmp/ia
                        mysql -u root --password="$pass" </tmp/ia >/tmp/arch
		        arch=$(cat /tmp/arch)
                        if [ -z "$arch" ]; then
                                dialog --title "Error" --msgbox "No existe el Registro" 0 0
                                bandera=0
                        else
                                dialog --title "Informacion" --textbox "/tmp/arch" 0 0
                        fi


                        bandera=0
                fi
        fi
done
fi

#3ra opcion borra por medio de id
if [ "$slc" -eq 3 ]; then
bandera=1
until [ "$bandera" -eq 0 ]
do
	mysql -u root --password="$pass" </tmp/sel >/tmp/arch
        arch=$(cat /tmp/arch)
        dialog --title "Informacion" --textbox "/tmp/arch" 0 0

	dialog --title "Eliminar info" --inputbox "Selecciona un Id a borrar" 0 0 2>/tmp/del.$$
	if  [ $? -eq 1 ];
	then
        	bandera=0
	fi

	del=$(cat /tmp/del.$$)
	S=$(echo "$del" | egrep "[[:digit:]]+")
	if [ -n "$S" ]; then
		#se verifica que quiera borar la informacion
		echo "use medidas;
                select * from Info where Id in ("$S");" > /tmp/ia
                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
                arch=$(cat /tmp/arch)
		if [ -z "$arch" ]; then
			dialog --title "Error" --msgbox "No existe el ID" 0 0
			bandera=0
		else
			dialog --title "Confirmar borrado" --msgbox "Se borrara la siguiente informacion\n
					$arch" 0 0
			dialog --yesno "Confirmar" 0 0
			if  [ $? -eq 1 ];
		        then
                		bandera=0
			else
				 #se crea un archivo para borrar informacion
		                echo "use medidas;
	        	        Delete from Info where Id="$del";" > /tmp/del

		                mysql -u root --password="$pass"</tmp/del
		                dialog --msgbox "Se elimino el Id $del" 0 0
                		bandera=0
		        fi
		fi
        else
                dialog --title "Error" --msgbox "ID invalido, vuelva a intentarlo" 0 0
        fi
done
fi

#4ta opcion modifica un campo por Id
if [ "$slc" -eq 4 ]; then
bandera=1
until [ "$bandera" -eq 0 ]
do
	mysql -u root --password="$pass" </tmp/sel >/tmp/arch
	arch=$(cat /tmp/arch)
	dialog --title "Informacion" --textbox "/tmp/arch" 0 0
        dialog --title "Modificar info" --inputbox "Selecciona un Id a modificar" 0 0 2>/tmp/mod.$$
	if  [ $? -eq 1 ];
	then
        	bandera=0
	fi
	#se verifica si existe el ID
		S=$(cat /tmp/mod.$$)
		echo "use medidas;
                select * from Info where Id in ("$S");" > /tmp/ia
                mysql -u root --password="$pass" </tmp/ia >/tmp/arch
                arch=$(cat /tmp/arch)
                if [ -z "$arch" ]; then
                        dialog --title "Error" --msgbox "No existe el ID" 0 0
                        bandera=0
                else
                        dialog --title "Confirmar modificacion" --msgbox "Se modificara la siguiente informacion\n
                                        $arch" 0 0
                        dialog --yesno "Confirmar" 0 0
                        if  [ $? -eq 1 ];
                        then
                                bandera=0
                        else
                                 #se procede a modificar informacion
				mod=$(cat /tmp/mod.$$)

        M=$(echo "$mod" | egrep "[[:digit:]]+")
        if [ -n "$M" ]; then
		#se debe poner los datos a modificar
		#edad
		dialog --title "Modificar info" --inputbox "$arch\n Ingrese edad" 0 0 2>/tmp/m.edad.$$
		edad=$(cat /tmp/m.edad.$$)
		E=$(echo "$edad" | egrep "[[:digit:]]+")
		if [ -n "$E" ]; then
			#ahora se valida estatura
			dialog --title "Modificar info" --inputbox "$arch\n Ingrese estatura" 0 0 2>/tmp/m.estatura.$$
	                estatura=$(cat /tmp/m.estatura.$$)
        	        E=$(echo "$estatura" | egrep "[[:digit:]]+")
                	if [ -n "$E" ]; then
				#ahora se valida Peso
				dialog --title "Modificar info" --inputbox "$arch\n Ingrese peso" 0 0 2>/tmp/m.peso.$$
	                	peso=$(cat /tmp/m.peso.$$)
	        	        E=$(echo "$peso" | egrep "[[:digit:]]+")
	                	if [ -n "$E" ]; then
					#aqui ya se valida promedio
					dialog --title "Modificar info" --inputbox "$arch\n Ingrese promedio" 0 0 2>/tmp/m.edad.$$
			                promedio=$(cat /tmp/m.edad.$$)
	                		E=$(echo "$edad" | egrep "[[:digit:]]+")
			                if [ -n "$E" ]; then
						#con estos valores ya validados se hace un archivo y se modifica la base
						 #se crea un archivo para borrar informacion
				                echo "use medidas;
				                update Info
						set Edad='$edad',
						Estatura='$estatura',
						Peso='$peso',
						Promedio='$promedio' 
						where Id='$mod';" >/tmp/mod

				                mysql -u root --password="$pass"</tmp/mod
				                dialog --infobox "Se modifico el Id $mod" 0 0; sleep 3

				                bandera=0
					else
						 dialog --msgbox "Algo salio mal, vuelve a intentarlo [4]" 0 0
					fi
				else
					 dialog --msgbox "Algo salio mal, vuelve a intentarlo [3]" 0 0
				fi

			else
				 dialog --msgbox "Algo salio mal, vuelve a intentarlo [2]" 0 0
			fi
		else
			 dialog --msgbox "Algo salio mal, vuelve a intentarlo [4]" 0 0

		fi
        else
		 dialog --msgbox "Id invalido, vuelva a intentarlo" 0 0
        fi

                        fi
                fi
done
fi


#2da opcion inserta informacion
if [ "$slc" -eq 2 ]; then
bandera=1
until [ "$bandera" -eq 0 ]
do
		#se debe poner los datos a insertar
		#edad
		dialog --title "Insertar info" --inputbox "Ingrese edad" 0 0 2>/tmp/i.edad.$$
		if  [ $? -eq 1 ];
		then
		        bandera=0
		fi

		edad=$(cat /tmp/i.edad.$$)
		E=$(echo "$edad" | egrep "[[:digit:]]+")
		if [ -n "$E" ]; then
			#ahora se valida estatura
			dialog --title "Insertar info" --inputbox "Ingrese estatura" 0 0 2>/tmp/i.estatura.$$
	                estatura=$(cat /tmp/i.estatura.$$)
        	        E=$(echo "$estatura" | egrep "[[:digit:]]+")
                	if [ -n "$E" ]; then
				#ahora se valida Peso
				dialog --title "Insertar info" --inputbox "Ingrese peso" 0 0 2>/tmp/i.peso.$$
	                	peso=$(cat /tmp/i.peso.$$)
	        	        E=$(echo "$peso" | egrep "[[:digit:]]+")
	                	if [ -n "$E" ]; then
					#aqui ya se valida promedio
					dialog --title "Insertar info" --inputbox "Ingrese promedio" 0 0 2>/tmp/i.edad.$$
			                promedio=$(cat /tmp/i.edad.$$)
	                		E=$(echo "$edad" | egrep "[[:digit:]]+")
			                if [ -n "$E" ]; then
						#con estos valores ya validados se hace un archivo y se modifica la base
						 #se crea un archivo para borrar informacion
				                echo "use medidas;
						insert into Info values 
						($contador,$edad,$estatura,$peso,$promedio,\"masculino\");">/tmp/ins

				                mysql -u root --password="$pass"</tmp/ins
				                dialog --infobox "Se inserto los Datos con ID $contador" 0 0; sleep 3

				                bandera=0
					else
						dialog --msgbox "Algo salio mal, vuelve a intentarlo [4]" 0 0
					fi
				else
					 dialog --msgbox "Algo salio mal, vuelve a intentarlo [3]" 0 0
				fi

			else
				 dialog --msgbox "Algo salio mal, vuelve a intentarlo [2]" 0 0
			fi
		else
			 dialog --msgbox "Algo salio mal, vuelve a intentarlo [1]" 0 0
		fi
done
contador=$(expr $contador + 1)
fi

#5ta opcion da reportes
if [ "$slc" -eq 5 ]; then
bandera=1
until [ "$bandera" -eq 0 ] #Iniciamos el ciclo del menu de las banderas
do
dialog --radiolist "¿Que tipo de grafica desea ver?" 0 0 0 1 "Estatura de acorde a Edad" on 2 "Peso de acorde a Edad" off 3 "Estatura de acorde a Peso" off 4 "Salir" off 2>/tmp/lk.$$
if [ $? -eq 1 ] #Verificamos si no dio a la opcion CANCEL
then
	bandera=0 
fi

contador=1

lk=$(cat /tmp/lk.$$) 	#En caso de que no, guardamos su respuesta

#Peso y Estatura
echo "use medidas;
select AVG(Peso) from Info
where Estatura between 150 AND 160;" >/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val1=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select AVG(Peso) from Info
where Estatura between 161 AND 170">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val2=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select (Peso) from Info
where Estatura between 171 AND 180">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val3=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select (Peso) from Info
where Estatura between 181 AND 190">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val4=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo -e " 150-160 $val1\n
	161-170 $val2\n
	171-180 $val3\n
	181-190 $val4" >/tmp/arch1

#Edad Estatura
echo "use medidas;
select AVG(Edad) from Info
where Estatura between 150 AND 160;" >/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val1=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select AVG(Edad) from Info
where Estatura between 161 AND 170">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val2=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select (Edad) from Info
where Estatura between 171 AND 180">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val3=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select (Edad) from Info
where Estatura between 181 AND 190">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val4=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo -e " 150-160 $val1\n
        161-170 $val2\n
        171-180 $val3\n
        181-190 $val4" >/tmp/arch2

#Peso y Edad
echo "use medidas;
select AVG(Peso) from Info
where Edad between 18 AND 18;" >/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val1=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select AVG(Peso) from Info
where Edad between 19 AND 19">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val2=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select (Peso) from Info
where Edad between 20 AND 20">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val3=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo "use medidas;
select (Peso) from Info
where Edad between 21 AND 21">/tmp/ia
mysql -u root --password="$pass" </tmp/ia >/tmp/ia2 #La guardamos en una variable
val4=$(cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g')

echo -e " 18 $val1\n
        19 $val2\n
        20 $val3\n
        21 $val4" >/tmp/arch3



#Sacamos toda la info de la BD
mysql -u root --password="$pass" </tmp/ia.dat >/tmp/ia2 #La guardamos en una variable
cat /tmp/ia2 | sed '1d' | sed 's/\t/ /g'> /tmp/ia.dat #sobre escribimos la variable pero con la info. limpia
case $lk in #Checamos que opcion eligio
1)
	gnuplot -persist <<-EOF #iniciamos el gnuplot para graficar
	set term png	#definimos la extension en la que saldra el archivo
	set output "grafica.png"	#decimos como se llamara el archivo
	set xlabel "Estatura"	#definimos cual sera la variante X
	set ylabel "Peso"	#definimos cual sera la variante Y
	set linestyle 1 lt 1 lw 15
	set title "Estatura de los hombres de acorde a su Edad"	#Titulo de la grafica
	plot "/tmp/arch1" using 1:2 with imp ls 1
	#le decimos de que archivo sacara los datos a graficar y le especificamos las variantes X:Y
	EOF
	display grafica.png	#mostramos el producto
	;;
2)
        gnuplot -persist <<-EOF
        set term png
        set output "grafica.png"
        set xlabel "Estatura"
        set ylabel "Edad"
	set linestyle 1 lt 1 lw 15
        set title "Peso de los hombres de acorde a su Edad"
        plot "/tmp/arch2" using 1:2 with imp ls 1

	EOF
	display grafica.png
	;;
3)
        gnuplot -persist <<-EOF
        set term png
        set output "grafica.png"
        set xlabel "Edad"
        set ylabel "Peso"
	set linestyle 1 lt 1 lw 15
        set title "Estatura de los hombres de acorde a su Edad" #Titulo de la grafica
        plot "/tmp/arch3" using 1:2 with imp ls 1
	EOF
	display grafica.png
	;;
4)
	bandera=0	#verificamos si quiere salir
	;;
esac
done
fi


#6ta opcion sale del ciclo
if [ "$slc" -eq 6 ]; then
	bandera=2
#	rm /tmp/*

	clear
fi

done #fin del ciclo maestro


exit 0
